#server
server:
  port: 80
  tomcat:
    max-threads: 1000
  servlet:
    context-path: /
  error:
    whitelabel:
      enabled: true
#spring datasource
spring:
  datasource:
    url: jdbc:mysql:///jtsys?serverTimezone=GMT%2B8&characterEncoding=UTF8
    username: root
    password: root
  thymeleaf:
    prefix: classpath:/templates/pages/
    suffix: .html
  aop:
    proxy-target-class: false
#Spring mybatis
mybatis:
  configuration:
    default-statement-timeout: 30
    map-underscore-to-camel-case: true
  mapper-locations:
  - classpath:/mapper/sys/*.xml

logging:
  level:
    com.cy: DEBUG
    














  
    
    
    
    
    
    
    